### ISSUE TITLE
[ContributionCounter] Database locks up when adding contributions

### ISSUE THREAD

**Issue by rclim95** [rclim95/StardewValleyMods#7]
The mod crashed with the following error:
```
[21:43:16 ERROR ContributionCounter] This mod failed in the MultiplayerEvents.AfterMainBroadcast event. Technical details:
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
at System.Data.SQLite.SQLiteDataReader.NextResult()
at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
at ContributionCounter.DatabaseQuerier.AddContribution(String worldName, String contributor, Contribution contribution) in D:\Projects\StardewValleyMods\ContributionCounter\DatabaseQuerier.cs:line 188
at ContributionCounter.ModEntry.OnAfterMainBroadcast(Object sender, EventArgs e) in D:\Projects\StardewValleyMods\ContributionCounter\ModEntry.cs:line 148
at StardewModdingAPI.Framework.Events.ManagedEvent.Raise() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 126
```

While I was playing as host, it crashed specifically once I got passed the menu that showed all the items shipped into the shipping menu. Seems like the SQLite database is getting locked up while synchronizing everyone's contributions that were sent to me (as host). 😞 

On a more interesting sidenote, the database was also locking up for players (Mellie and Tyler) who were playing on the farm I've hosted. Although, I'm not exactly sure what exactly caused that to happen (but most likely, it has to do with adding contributions since my sister reported a _database is locked_ error). 🤔

**Comment by rclim95** [comment]
Proposed solution by @Tready07 that was discussed earlier: Use a database queue! Database operations will be put inside a queue, and the game will periodically check this queue to see what the database needs to do, do it, and continue until there's nothing in the queue. 😄
